version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: intellivision
      POSTGRES_USER: adminvision
      POSTGRES_PASSWORD: IntelliVisionAIonOS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  web:
    build: .
    command: python intellivision/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - shared-tmp:/tmp
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_DB=intellivision
      - POSTGRES_USER=adminvision
      - POSTGRES_PASSWORD=IntelliVisionAIonOS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URI=mongodb+srv://toram444444:06nJTevaUItCDpd9@cluster01.lemxesc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster01
      - YOLO_CACHE_DIR=/app/intellivision/apps/video_analytics/models
      - JOB_OUTPUT_DIR=/app/intellivision/media/outputs
    depends_on:
      - db
      - redis
      - qdrant

  celery:
    build: .
    command: celery -A intellivision worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - shared-tmp:/tmp
    environment:
      - PYTHONPATH=/app/intellivision
      - POSTGRES_DB=intellivision
      - POSTGRES_USER=adminvision
      - POSTGRES_PASSWORD=IntelliVisionAIonOS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URI=mongodb+srv://toram444444:06nJTevaUItCDpd9@cluster01.lemxesc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster01
      - YOLO_CACHE_DIR=/app/intellivision/apps/video_analytics/models
      - JOB_OUTPUT_DIR=/app/intellivision/media/outputs
    depends_on:
      - db
      - redis
      - qdrant

volumes:
  postgres_data:
  qdrant_data:
  shared-tmp:
