# Generated by Django 5.2.3 on 2025-06-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='person_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
