# Generated by Django 5.2.3 on 2025-06-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_videojob_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='car_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='in_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='job_type',
            field=models.CharField(default='people_count', max_length=50),
        ),
        migrations.AddField(
            model_name='videojob',
            name='out_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
