# Generated by Django 5.2.3 on 2025-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_videojob_car_count_videojob_in_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='car_count',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='in_count',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='out_count',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='person_count',
        ),
        migrations.AddField(
            model_name='videojob',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='job_type',
            field=models.CharField(choices=[('people_count', 'People Counting'), ('car_count', 'Car Counting'), ('pothole_detection', 'Pothole Detection'), ('food_waste_estimation', 'Food Waste Estimation'), ('pest_monitoring', 'Pest Monitoring')], default='people_count', max_length=50),
        ),
    ]
