# Generated by Django 5.2.3 on 2025-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_videojob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='job_type',
            field=models.CharField(choices=[('people_count', 'People Counting'), ('emergency_count', 'Emergency Analysis'), ('car_count', 'Car Counting'), ('pothole_detection', 'Pothole Detection'), ('food_waste_estimation', 'Food Waste Estimation'), ('pest_monitoring', 'Pest Monitoring'), ('wildlife_detection', 'Wildlife Detection')], default='people_count', max_length=50),
        ),
    ]
