# Generated by Django 5.2.3 on 2025-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_videojob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='roi_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='roi_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='roi_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='roi_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
