# Generated by Django 5.2.3 on 2025-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analytics', '0002_alter_videojob_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='line1_end_x',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line1_end_y',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line1_start_x',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line1_start_y',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line2_end_x',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line2_end_y',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line2_start_x',
        ),
        migrations.RemoveField(
            model_name='videojob',
            name='line2_start_y',
        ),
        migrations.AddField(
            model_name='videojob',
            name='emergency_lines',
            field=models.JSONField(blank=True, help_text='List of lines for emergency_count, each as dict with start/end x/y', null=True),
        ),
    ]
