# Generated by Django 5.2.3 on 2025-07-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analytics', '0003_remove_videojob_line1_end_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='lobby_zones',
            field=models.JSONField(blank=True, help_text="List of zones for lobby/crowd detection, each as dict with 'points' (list of [x, y]) and 'threshold' (int)", null=True),
        ),
    ]
