# Generated by Django 5.2.3 on 2025-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analytics', '0004_videojob_lobby_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='job_type',
            field=models.CharField(choices=[('people_count', 'People Counting'), ('emergency_count', 'Emergency Analysis'), ('car_count', 'Car Counting'), ('pothole_detection', 'Pothole Detection'), ('food_waste_estimation', 'Food Waste Estimation'), ('room_readiness', 'Room Readiness Analysis'), ('wildlife_detection', 'Wildlife Detection')], default='people_count', help_text='Type of analytics job.', max_length=50),
        ),
    ]
