# Generated by Django 5.2.3 on 2025-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analytics', '0006_videojob_youtube_url_alter_videojob_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='task_id',
            field=models.CharField(blank=True, help_text='The Celery task ID for this job, used for task revocation and monitoring.', max_length=255, null=True),
        ),
    ]
